package tools

import (
	"os"
	"path/filepath"
)

func init() {
	Register(&Powerlevel10k{})
}

// Powerlevel10k provides powerlevel10k zsh theme configuration.
// The theme can display sandbox indicator using DEVSANDBOX env var.
type Powerlevel10k struct{}

func (p *Powerlevel10k) Name() string {
	return "powerlevel10k"
}

func (p *Powerlevel10k) Description() string {
	return "Powerlevel10k zsh theme"
}

func (p *Powerlevel10k) Available(homeDir string) bool {
	// Check common powerlevel10k locations
	paths := []string{
		filepath.Join(homeDir, ".oh-my-zsh", "custom", "themes", "powerlevel10k"),
		filepath.Join(homeDir, ".local", "share", "powerlevel10k"),
		filepath.Join(homeDir, "powerlevel10k"),
		filepath.Join(homeDir, ".p10k.zsh"),
	}

	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}

	return false
}

func (p *Powerlevel10k) Bindings(homeDir, sandboxHome string) []Binding {
	sandboxP10k := filepath.Join(sandboxHome, ".p10k.zsh")

	bindings := []Binding{
		// Powerlevel10k installation paths
		{Source: filepath.Join(homeDir, ".oh-my-zsh", "custom", "themes", "powerlevel10k"), Category: CategoryData, Optional: true},
		{Source: filepath.Join(homeDir, ".local", "share", "powerlevel10k"), Category: CategoryData, Optional: true},
		{Source: filepath.Join(homeDir, "powerlevel10k"), Category: CategoryData, Optional: true},
		// Powerlevel10k cache (for instant prompt)
		{Source: filepath.Join(homeDir, ".cache", "p10k-instant-prompt-"+os.Getenv("USER")+".zsh"), Category: CategoryCache, Optional: true},
	}

	// Use sandbox p10k config if setup ran successfully
	if _, err := os.Stat(sandboxP10k); err == nil {
		bindings = append(bindings, Binding{
			Source:   sandboxP10k,
			Dest:     filepath.Join(homeDir, ".p10k.zsh"),
			Category: CategoryConfig,
			Optional: true,
		})
	} else {
		// Fall back to original config
		bindings = append(bindings, Binding{
			Source:   filepath.Join(homeDir, ".p10k.zsh"),
			Category: CategoryConfig,
			Optional: true,
		})
	}

	return bindings
}

func (p *Powerlevel10k) Environment(homeDir, sandboxHome string) []EnvVar {
	return nil
}

func (p *Powerlevel10k) ShellInit(shell string) string {
	return ""
}

func (p *Powerlevel10k) Check(homeDir string) CheckResult {
	result := CheckResult{
		BinaryName:  "p10k",
		InstallHint: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.local/share/powerlevel10k",
	}

	// Check installation paths
	installPaths := []string{
		filepath.Join(homeDir, ".oh-my-zsh", "custom", "themes", "powerlevel10k"),
		filepath.Join(homeDir, ".local", "share", "powerlevel10k"),
		filepath.Join(homeDir, "powerlevel10k"),
	}

	for _, path := range installPaths {
		if _, err := os.Stat(path); err == nil {
			result.ConfigPaths = append(result.ConfigPaths, path)
			result.Available = true
		}
	}

	// Check p10k config
	p10kConfig := filepath.Join(homeDir, ".p10k.zsh")
	if _, err := os.Stat(p10kConfig); err == nil {
		result.ConfigPaths = append(result.ConfigPaths, p10kConfig)
	}

	if !result.Available {
		result.Issues = append(result.Issues, "powerlevel10k not found in common locations")
	}

	return result
}

// Setup implements ToolWithSetup to generate the sandbox-aware p10k config.
func (p *Powerlevel10k) Setup(homeDir, sandboxHome string) error {
	p10kConfig := filepath.Join(homeDir, ".p10k.zsh")
	sandboxP10k := filepath.Join(sandboxHome, ".p10k.zsh")

	// Check if p10k config exists
	if _, err := os.Stat(p10kConfig); os.IsNotExist(err) {
		return nil
	}

	// Read original config
	original, err := os.ReadFile(p10kConfig)
	if err != nil {
		return err
	}

	// Append sandbox indicator function
	// This adds a custom segment that shows when DEVSANDBOX is set
	indicator := `

# Sandbox indicator (auto-generated by devsandbox)
# Shows when running inside devsandbox
function prompt_devsandbox() {
  if [[ -n "$DEVSANDBOX" ]]; then
    p10k segment -f 196 -i '' -t "[sandbox${DEVSANDBOX_PROJECT:+:$DEVSANDBOX_PROJECT}]"
  fi
}

# Add devsandbox to POWERLEVEL9K_LEFT_PROMPT_ELEMENTS if not already present
if [[ ! " ${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[*]} " =~ " devsandbox " ]]; then
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(devsandbox "${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[@]}")
fi
`
	modified := string(original) + indicator

	return os.WriteFile(sandboxP10k, []byte(modified), 0o644)
}
