package tools

import (
	"os"
	"os/exec"
	"path/filepath"
)

func init() {
	Register(&Starship{})
}

// Starship provides starship prompt configuration.
// Creates a modified config with a sandbox indicator.
type Starship struct{}

func (s *Starship) Name() string {
	return "starship"
}

func (s *Starship) Description() string {
	return "Starship prompt with sandbox indicator"
}

func (s *Starship) Available(homeDir string) bool {
	// Check if starship is installed and user has a config
	if _, err := exec.LookPath("starship"); err != nil {
		return false
	}
	starshipConfig := filepath.Join(homeDir, ".config", "starship.toml")
	_, err := os.Stat(starshipConfig)
	return err == nil
}

func (s *Starship) Bindings(homeDir, sandboxHome string) []Binding {
	starshipConfig := filepath.Join(homeDir, ".config", "starship.toml")
	sandboxStarshipConfig := filepath.Join(sandboxHome, ".config", "starship.toml")

	return []Binding{
		{
			Source:   sandboxStarshipConfig,
			Dest:     starshipConfig,
			Category: CategoryConfig,
			Optional: true, // Might not exist if setup failed
		},
	}
}

func (s *Starship) Environment(homeDir, sandboxHome string) []EnvVar {
	return nil
}

func (s *Starship) ShellInit(shell string) string {
	return ""
}

func (s *Starship) Check(homeDir string) CheckResult {
	result := CheckBinary("starship", "mise install starship")
	if !result.Available {
		return result
	}

	// Check config - starship requires config to be available
	starshipConfig := filepath.Join(homeDir, ".config", "starship.toml")
	result.AddConfigPath(starshipConfig)

	if len(result.ConfigPaths) == 0 {
		result.Available = false
		result.AddIssue("no ~/.config/starship.toml found")
	}

	return result
}

// Setup implements ToolWithSetup to generate the sandbox-aware starship config.
func (s *Starship) Setup(homeDir, sandboxHome string) error {
	srcPath := filepath.Join(homeDir, ".config", "starship.toml")
	destPath := filepath.Join(sandboxHome, ".config", "starship.toml")

	indicator := `

# Sandbox indicator (auto-generated by devsandbox)
[custom.devsandbox]
command = "echo [sandboxed]"
when = true
format = "[$output]($style) "
style = "bold red"
shell = ["sh"]
`
	return SetupConfigWithSuffix(srcPath, destPath, indicator)
}
