package tools

import (
	"os"
	"os/exec"
	"path/filepath"
)

func init() {
	Register(&Starship{})
}

// Starship provides starship prompt configuration.
// Creates a modified config with a sandbox indicator.
type Starship struct{}

func (s *Starship) Name() string {
	return "starship"
}

func (s *Starship) Available(homeDir string) bool {
	// Check if starship is installed and user has a config
	if _, err := exec.LookPath("starship"); err != nil {
		return false
	}
	starshipConfig := filepath.Join(homeDir, ".config", "starship.toml")
	_, err := os.Stat(starshipConfig)
	return err == nil
}

func (s *Starship) Bindings(homeDir, sandboxHome string) []Binding {
	starshipConfig := filepath.Join(homeDir, ".config", "starship.toml")
	sandboxStarshipConfig := filepath.Join(sandboxHome, ".config", "starship.toml")

	return []Binding{
		{
			Source:   sandboxStarshipConfig,
			Dest:     starshipConfig,
			ReadOnly: true,
			Optional: true, // Might not exist if setup failed
		},
	}
}

func (s *Starship) Environment(homeDir, sandboxHome string) []EnvVar {
	return nil
}

func (s *Starship) ShellInit(shell string) string {
	return ""
}

// Setup implements ToolWithSetup to generate the sandbox-aware starship config.
func (s *Starship) Setup(homeDir, sandboxHome string) error {
	starshipConfig := filepath.Join(homeDir, ".config", "starship.toml")
	sandboxStarshipConfig := filepath.Join(sandboxHome, ".config", "starship.toml")

	// Check if starship config exists
	if _, err := os.Stat(starshipConfig); os.IsNotExist(err) {
		return nil
	}

	// Create config directory in sandbox home
	configDir := filepath.Join(sandboxHome, ".config")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return err
	}

	// Read original config
	original, err := os.ReadFile(starshipConfig)
	if err != nil {
		return err
	}

	// Append sandbox indicator (at the end to avoid $schema issues)
	indicator := `

# Sandbox indicator (auto-generated by devsandbox)
[custom.devsandbox]
command = "echo [sandboxed]"
when = true
format = "[$output]($style) "
style = "bold red"
shell = ["sh"]
`
	modified := string(original) + indicator

	return os.WriteFile(sandboxStarshipConfig, []byte(modified), 0o644)
}
