version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  exclusions:
    paths:
      - vendor
      - tmp
    rules:
      - path: '_test\.go'
        linters:
          - staticcheck
        text: "SA5011"
