version: 2

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/devsandbox
    binary: devsandbox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X devsandbox/internal/version.Version={{ .Version }}
      - -X devsandbox/internal/version.Commit={{ .ShortCommit }}
      - -X devsandbox/internal/version.Date={{ .Date }}
      - -X devsandbox/internal/version.Dirty={{ if .IsSnapshot }}true{{ else }}false{{ end }}

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^example:'
