repos:
  - repo: local
    hooks:
      - id: vet
        name: go vet
        entry: task vet
        language: system
        pass_filenames: false
        types: [go]

      - id: fmt
        name: gofmt
        entry: task fmt
        language: system
        pass_filenames: false
        types: [go]

      - id: cross-test
        name: cross-platform test compile
        entry: task cross-test
        language: system
        pass_filenames: false
        types: [go]

      - id: cross-build
        name: cross-platform build
        entry: task cross-build
        language: system
        pass_filenames: false
        types: [go]
