version: "3"

vars:
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "dev"
  BUILD_DATE:
    sh: date --iso-8601=seconds
  GIT_DIRTY:
    sh: test -n "$(git status --porcelain 2>/dev/null)" && echo "true" || echo "false"
  # Hash of uncommitted changes (short md5 of git diff output)
  GIT_DIRTY_HASH:
    sh: |
      if [ "$(git status --porcelain 2>/dev/null)" ]; then
        git diff HEAD 2>/dev/null | md5sum | cut -c1-7
      else
        echo ""
      fi

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    deps:
      - vet
      - fmt
      - golangci

  vet:
    cmds:
      - go vet ./...

  fmt:
    cmds:
      - gofmt -l -w -s ./

  golangci:
    cmds:
      - golangci-lint run --modules-download-mode readonly --timeout=10m

  test:
    cmds:
      - go test ./internal/...

  test:e2e:
    cmds:
      - go test -v ./e2e/...

  test:all:
    cmds:
      - go test -v ./...

  build:
    cmds:
      - mkdir -p bin
      - go build -ldflags "-X devsandbox/internal/version.Commit={{.GIT_COMMIT}} -X devsandbox/internal/version.Date={{.BUILD_DATE}} -X devsandbox/internal/version.Dirty={{.GIT_DIRTY}} -X devsandbox/internal/version.DirtyHash={{.GIT_DIRTY_HASH}}" -o bin/devsandbox ./cmd/devsandbox

  archive:
    desc: Create source archive for sharing (includes all files needed to build)
    vars:
      ARCHIVE_NAME:
        sh: |
          if [ "{{.GIT_DIRTY}}" = "true" ]; then
            echo "devsandbox_{{.GIT_COMMIT}}-dirty-{{.GIT_DIRTY_HASH}}"
          else
            echo "devsandbox_{{.GIT_COMMIT}}"
          fi
    cmds:
      - mkdir -p bin
      - rm -f bin/devsandbox_*.tar.gz bin/devsandbox_*.zip || true
      - |
        tar --transform 's,^,{{.ARCHIVE_NAME}}/,' \
          --exclude='.git' \
          --exclude='.idea' \
          --exclude='.claude' \
          --exclude='.serena' \
          --exclude='claudedocs' \
          --exclude='bin' \
          --exclude='*.tar.gz' \
          --exclude='*.zip' \
          -czvf bin/{{.ARCHIVE_NAME}}.tar.gz \
          cmd/ internal/ e2e/ docs/ \
          go.mod go.sum \
          Taskfile.yaml .mise.toml .gitignore \
          README.md CLAUDE.md
      - echo "Created bin/{{.ARCHIVE_NAME}}.tar.gz"

  archive:bin:
    desc: Create binary release archive
    deps:
      - build
    cmds:
      - rm -f bin/devsandbox_*_bin.zip || true
      - zip -j bin/devsandbox_{{.GIT_COMMIT}}_bin.zip bin/devsandbox README.md
      - zip -r bin/devsandbox_{{.GIT_COMMIT}}_bin.zip docs/

  prune-local:
    cmds:
      - rm -rf ~/.local/share/devsandbox/
