version: "3"

vars:
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_DATE:
    sh: date --iso-8601=seconds
  GIT_DIRTY:
    sh: test -n "$(git status --porcelain 2>/dev/null)" && echo "true" || echo "false"
  # Hash of uncommitted changes (short md5 of git diff output)
  GIT_DIRTY_HASH:
    sh: |
      if [ "$(git status --porcelain 2>/dev/null)" ]; then
        git diff HEAD 2>/dev/null | md5sum | cut -c1-7
      else
        echo ""
      fi
  # Git tag for the current commit, or "dev" if not tagged
  GIT_VERSION:
    sh: git describe --tags --exact-match 2>/dev/null || echo "dev"

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    deps:
      - vet
      - fmt
      - golangci

  vet:
    cmds:
      - go vet ./...

  fmt:
    cmds:
      - gofmt -l -w -s ./

  golangci:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test ./internal/...

  test:e2e:
    cmds:
      - go test -v ./e2e/...

  test:all:
    cmds:
      - go test -v ./...

  build:
    desc: Build binary for local development
    cmds:
      - mkdir -p bin
      - go build -ldflags "-X devsandbox/internal/version.Version={{.GIT_VERSION}} -X devsandbox/internal/version.Commit={{.GIT_COMMIT}} -X devsandbox/internal/version.Date={{.BUILD_DATE}} -X devsandbox/internal/version.Dirty={{.GIT_DIRTY}} -X devsandbox/internal/version.DirtyHash={{.GIT_DIRTY_HASH}}" -o bin/devsandbox ./cmd/devsandbox

  release:snapshot:
    desc: Build snapshot release using goreleaser (for testing)
    cmds:
      - goreleaser release --snapshot --clean

  prune-local:
    cmds:
      - rm -rf ~/.local/share/devsandbox/
