version: "3"

vars:
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "dev"
  BUILD_DATE:
    sh: date --iso-8601=seconds

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    deps:
      - vet
      - fmt
      - golangci

  vet:
    cmds:
      - go vet ./...

  fmt:
    cmds:
      - gofmt -l -w -s ./

  golangci:
    cmds:
      - golangci-lint run --modules-download-mode readonly --timeout=10m

  test:
    cmds:
      - go test ./internal/...

  test:e2e:
    cmds:
      - go test -v ./e2e/...

  test:all:
    cmds:
      - go test -v ./...

  build:
    cmds:
      - mkdir -p bin
      - go build -ldflags "-X main.version={{.GIT_COMMIT}} -X main.date={{.BUILD_DATE}}" -o bin/devsandbox ./cmd/devsandbox

  archive:
    deps:
      - build
    cmds:
      - zip -j bin/devsandbox_{{.GIT_COMMIT}}.zip bin/devsandbox README.md
