// Package shellwrap generates the host shell snippets that make supported AI
// agents run inside devsandbox by default: typing `claude` runs
// `devsandbox run-agent claude`, while `claude-no-ds` and `command claude`
// still reach the real binary.
//
// The generated snippet is read inside the sandbox too - the sandbox binds
// fish's conf.d and bash/zsh rc files - so every definition is wrapped in a
// guard on DEVSANDBOX, the marker the sandbox builder sets. The guard uses
// non-empty semantics in every shell: an empty DEVSANDBOX means "outside the
// sandbox" everywhere, matching what the run-agent entrypoint checks in Go.
//
// The package is a stdlib-only leaf so both the wrapper CLI and run-agent can
// import it without dragging in the tool registry.
package shellwrap

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// Header is the first line of every generated snippet. Installation uses it to
// tell a file devsandbox wrote from one the user maintains, and refuses to
// touch a file that does not carry it.
const Header = "# generated by devsandbox; manage via `devsandbox agent-wrappers`"

// Supported shell names.
const (
	ShellFish = "fish"
	ShellBash = "bash"
	ShellZsh  = "zsh"
)

// supportedShells is the single list both SupportedShells and IsSupportedShell
// answer from, so a shell can never be generatable but unlisted.
var supportedShells = []string{ShellFish, ShellBash, ShellZsh}

// SupportedShells returns the shells a snippet can be generated for, in a
// stable order.
func SupportedShells() []string {
	return slices.Clone(supportedShells)
}

// IsSupportedShell reports whether Snippet can generate for shell.
func IsSupportedShell(shell string) bool {
	return slices.Contains(supportedShells, shell)
}

// Snippet returns the wrapper definitions for shell.
//
// devsandboxPath must be devsandbox's absolute path, resolved at install time.
// A herdr pane shell may be a login shell whose PATH differs from the one
// `install` ran in - mise shims being the common case - and a bare
// `devsandbox` would then fail with command-not-found in exactly the situation
// the wrapper exists to serve.
//
// The path is checked before it is used, and a missing binary fails closed with
// the reinstall command rather than falling back to a PATH lookup. The
// documented install (`mise use -g github:zekker6/devsandbox`) resolves to a
// version-scoped directory, so an upgrade moves the binary and makes that check
// fail on a normal machine - but resolving `devsandbox` through PATH there would
// hand the host shell whatever binary PATH names first, and a project-local bin
// directory on PATH is writable by the sandbox that devsandbox is meant to
// contain. `run-agent` refuses a PATH lookup for the same reason; the snippet
// must not reintroduce one at the shell layer.
//
// That diagnostic goes through printf, not echo: zsh's echo expands backslash
// escapes by default and bash's does under xpg_echo, so a path containing `\c`
// would truncate the message before the reinstall command it exists to name.
// printf expands escapes in its format string only, never in a %s argument.
func Snippet(shell, devsandboxPath string, agents []string) (string, error) {
	if !IsSupportedShell(shell) {
		return "", fmt.Errorf("unsupported shell %q: supported shells are %s",
			shell, strings.Join(SupportedShells(), ", "))
	}
	if !filepath.IsAbs(devsandboxPath) {
		return "", fmt.Errorf("devsandbox path %q must be absolute", devsandboxPath)
	}
	if len(agents) == 0 {
		return "", fmt.Errorf("no agents to wrap")
	}
	for _, a := range agents {
		if err := validateAgentName(a); err != nil {
			return "", err
		}
	}

	if shell == ShellFish {
		return fishSnippet(devsandboxPath, agents), nil
	}
	return posixSnippet(devsandboxPath, agents), nil
}

func fishSnippet(devsandboxPath string, agents []string) string {
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString("if test -z \"$DEVSANDBOX\"\n")
	q := fishQuote(devsandboxPath)
	for _, a := range agents {
		fmt.Fprintf(&b, "    function %s --wraps %s\n", a, a)
		fmt.Fprintf(&b, "        if test -x %s\n", q)
		fmt.Fprintf(&b, "            %s run-agent %s $argv\n", q, a)
		b.WriteString("        else\n")
		fmt.Fprintf(&b, "            printf '%%s %%s %%s\\n' \"devsandbox: no executable at\" %s \"- run 'devsandbox agent-wrappers install' to refresh the wrappers\" >&2\n", q)
		b.WriteString("            return 127\n")
		b.WriteString("        end\n")
		b.WriteString("    end\n")
		fmt.Fprintf(&b, "    function %s-no-ds --wraps %s\n", a, a)
		fmt.Fprintf(&b, "        command %s $argv\n", a)
		b.WriteString("    end\n")
	}
	b.WriteString("end\n")
	return b.String()
}

func posixSnippet(devsandboxPath string, agents []string) string {
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString("if [ -n \"${DEVSANDBOX:-}\" ]; then :; else\n")
	q := posixQuote(devsandboxPath)
	for _, a := range agents {
		fmt.Fprintf(&b, "  %s() { if [ -x %s ]; then %s run-agent %s \"$@\"; else printf '%%s %%s %%s\\n' \"devsandbox: no executable at\" %s \"- run 'devsandbox agent-wrappers install' to refresh the wrappers\" >&2; return 127; fi; }\n", a, q, q, a, q)
		fmt.Fprintf(&b, "  %s-no-ds() { command %s \"$@\"; }\n", a, a)
	}
	b.WriteString("fi\n")
	return b.String()
}

// InstallPath returns where shell's snippet belongs, honoring XDG_CONFIG_HOME
// (which is how fish itself resolves $__fish_config_dir). It returns "" for an
// unsupported shell.
//
// fish gets a conf.d drop-in, so no existing file is ever edited. bash and zsh
// have no drop-in directory, so they get a standalone file the user sources
// themselves via SourceLine.
func InstallPath(shell, homeDir string) string {
	config := os.Getenv("XDG_CONFIG_HOME")
	if !filepath.IsAbs(config) {
		config = filepath.Join(homeDir, ".config")
	}
	switch shell {
	case ShellFish:
		return filepath.Join(config, "fish", "conf.d", "devsandbox-agents.fish")
	case ShellBash, ShellZsh:
		return filepath.Join(config, "devsandbox", "agent-wrappers."+shell)
	}
	return ""
}

// SourceLine returns the line a bash or zsh user adds to their rc file. It is
// empty for fish, whose snippet is a drop-in.
//
// The line is existence-guarded on purpose: ~/.config/devsandbox is bound into
// the sandbox by nothing, while ~/.bashrc and ~/.zshrc are bound, so an
// unguarded source would error on every in-sandbox shell start.
func SourceLine(shell, path string) string {
	switch shell {
	case ShellBash, ShellZsh:
		q := posixQuote(path)
		return fmt.Sprintf("[ -r %s ] && . %s", q, q)
	}
	return ""
}

// validateAgentName rejects anything that is not a bare shell-safe word. Agent
// names are host-derived, but the generated text is executed by a shell, so
// the charset is pinned rather than assumed.
func validateAgentName(name string) error {
	if name == "" {
		return fmt.Errorf("empty agent name")
	}
	if name[0] == '-' {
		return fmt.Errorf("invalid agent name %q: must not start with %q", name, "-")
	}
	for i := 0; i < len(name); i++ {
		c := name[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '_', c == '-':
		default:
			return fmt.Errorf("invalid agent name %q: only [A-Za-z0-9_-] is allowed", name)
		}
	}
	return nil
}

// posixQuote single-quotes s for bash, zsh, and any POSIX shell.
func posixQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// fishQuote single-quotes s for fish, where only backslash and the quote
// itself are escapable inside single quotes.
func fishQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `'`, `\'`)
	return "'" + r.Replace(s) + "'"
}
